In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
df_clean_data = pd.read_csv('clean_data.csv')

In [16]:
df_clean_data

,Unnamed: 0,type_data,status_group,amount_tsh,count_month,funder,gps_height,installer,basin,public_meeting,...,construction_year,extraction_type_class,management,payment,quality_group,quantity,source,source_class,status_group_02,missing_construction_year
0,0,T,0,6000.0,4,other,1390.0,other,Lake Nyasa,True,...,1999.0,gravity,vwc,pay annually,good,enough,spring,groundwater,2,False
1,1,T,0,250.0,3,other,1399.0,other,Lake Victoria,Unknown,...,2010.0,gravity,wug,never pay,good,insufficient,rainwater harvesting,surface,2,False
2,2,T,0,25.0,3,other,686.0,other,Pangani,True,...,2009.0,gravity,vwc,pay per bucket,good,enough,dam,surface,2,False
3,3,T,0,250.0,3,unicef,263.0,other,Ruvuma / Southern Coast,True,...,1986.0,submersible,vwc,never pay,good,dry,machine dbh,groundwater,0,False
4,4,T,0,250.0,4,other,1166.0,other,Lake Victoria,True,...,2000.0,gravity,other,never pay,good,seasonal,rainwater harvesting,surface,2,True
5,5,T,0,20.0,4,other,1166.0,dwe,Pangani,True,...,2009.0,submersible,vwc,pay per bucket,salty,enough,other,unknown,2,False
6,6,T,0,250.0,4,other,1166.0,other,Internal,True,...,2000.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,0,True
7,7,T,0,250.0,4,rwssp,1166.0,dwe,Lake Tanganyika,True,...,2000.0,handpump,wug,other,milky,enough,shallow well,groundwater,0,True
8,8,T,0,250.0,3,other,1166.0,other,Lake Tanganyika,True,...,2000.0,handpump,vwc,never pay,salty,seasonal,machine dbh,groundwater,0,True
9,9,T,0,250.0,4,other,1166.0,other,Lake Victoria,True,...,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,2,True
10,10,T,0,250.0,4,other,62.0,other,Wami / Ruvu,True,...,2011.0,submersible,private operator,never pay,salty,enough,machine dbh,groundwater,2,False
11,11,T,0,200.0,3,danida,1062.0,danida,Lake Nyasa,True,...,1987.0,handpump,wug,pay when scheme fails,good,insufficient,shallow well,groundwater,2,False
12,12,T,0,250.0,4,world vision,1166.0,other,Internal,True,...,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,2,True
13,13,T,0,250.0,3,other,1368.0,other,Pangani,True,...,2009.0,gravity,water board,pay monthly,good,enough,spring,groundwater,2,False
14,14,T,0,250.0,3,other,1166.0,other,Internal,True,...,2000.0,handpump,wug,never pay,good,enough,shallow well,groundwater,2,True
15,15,T,0,250.0,4,other,1645.0,dwe,Lake Tanganyika,True,...,1991.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,2,False
16,16,T,0,500.0,4,unicef,1703.0,dwe,Rufiji,True,...,1978.0,gravity,wua,pay monthly,good,dry,river,surface,0,False
17,17,T,0,250.0,4,unicef,1656.0,dwe,Rufiji,True,...,1978.0,gravity,wua,pay when scheme fails,good,dry,river,surface,0,False
18,18,T,0,250.0,4,hesawa,1162.0,dwe,Lake Victoria,Unknown,...,1999.0,other,vwc,never pay,milky,insufficient,spring,groundwater,1,False
19,19,T,0,500.0,4,danida,1763.0,other,Lake Nyasa,True,...,1992.0,gravity,vwc,pay annually,good,enough,spring,groundwater,2,False
20,20,T,0,200.0,4,other,2216.0,other,Lake Nyasa,True,...,2008.0,gravity,vwc,pay monthly,good,enough,spring,groundwater,2,False
21,21,T,0,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,...,2000.0,handpump,wug,other,unknown,unknown,shallow well,groundwater,2,True
22,22,T,0,250.0,4,unicef,1510.0,dwe,Rufiji,True,...,1978.0,gravity,wua,never pay,good,enough,river,surface,1,False
23,23,T,0,500.0,3,other,672.0,other,Pangani,True,...,2011.0,gravity,vwc,pay monthly,good,enough,river,surface,2,False
24,24,T,0,250.0,3,other,1645.0,dwe,Lake Tanganyika,False,...,2009.0,gravity,vwc,other,good,enough,spring,groundwater,2,False
25,25,T,0,250.0,3,gov,1273.0,dwe,Pangani,True,...,1974.0,gravity,vwc,other,good,enough,spring,groundwater,1,False
26,26,T,0,500.0,3,other,200.0,other,Ruvuma / Southern Coast,False,...,2011.0,handpump,vwc,pay monthly,good,enough,machine dbh,groundwater,2,False
27,27,T,0,250.0,4,hesawa,1166.0,dwe,Lake Victoria,True,...,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,2,True
28,28,T,0,250.0,3,gov,1443.0,other,Pangani,True,...,2000.0,gravity,company,pay monthly,good,insufficient,spring,groundwater,0,False
29,29,T,0,250.0,3,other,1256.0,other,Pangani,True,...,2002.0,gravity,water board,pay monthly,good,enough,spring,groundwater,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,74220,P,0,250.0,3,other,265.0,other,Ruvuma / Southern Coast,True,...,2001.0,gravity,vwc,never pay,good,seasonal,rainwater harvesting,surface,3,False
74221,74221,P,0,5.0,3,other,1322.0,dwe,Pangani,True,...,2007.0,gravity,water board,pay per bucket,good,enough,river,surface,3,False
74222,74222,P,0,50.0,3,other,640.0,other,Ruvuma / Southern Coast,True,...,1997.0,gravity,other,pay per bucket,good,insufficient,spring,groundwater,3,False
74223,74223,P,0,250.0,4,other,1166.0,other,Lake Nyasa,True,...,2000.0,gravity,parastatal,other,good,enough,spring,groundwater,3,True
74224,74224,P,0,250.0,4,other,574.0,other,Wami / Ruvu,True,...,2008.0,handpump,vwc,never pay,good,insufficient,shallow well,groundwater,3,False
74225,74225,P,0,250.0,3,other,331.0,other,Ruvuma / Southern Coast,True,...,1978.0,handpump,vwc,never pay,good,insufficient,machine dbh,groundwater,3,False
74226,74226,P,0,250.0,3,world vision,1166.0,other,Lake Tanganyika,Unknown,...,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74227,74227,P,0,250.0,4,hesawa,1166.0,other,Lake Victoria,True,...,2000.0,handpump,vwc,pay annually,good,enough,shallow well,groundwater,3,True
74228,74228,P,0,50.0,4,other,78.0,other,Wami / Ruvu,False,...,2000.0,other,private operator,pay per bucket,salty,enough,machine dbh,groundwater,3,True
74229,74229,P,0,250.0,3,gov,836.0,gov,Ruvuma / Southern Coast,Unknown,...,2005.0,gravity,vwc,other,good,enough,spring,groundwater,3,False
74230,74230,P,0,250.0,3,other,1651.0,tcrs,Pangani,True,...,1996.0,gravity,vwc,never pay,good,insufficient,spring,groundwater,3,False
74231,74231,P,0,250.0,3,hesawa,1166.0,dwe,Lake Victoria,True,...,2000.0,handpump,vwc,never pay,salty,enough,shallow well,groundwater,3,True
74232,74232,P,0,250.0,3,kkkt,1393.0,kkkt,Pangani,True,...,2001.0,submersible,vwc,other,fluoride,enough,machine dbh,groundwater,3,False
74233,74233,P,0,1000.0,4,kkkt,1729.0,commu,Lake Nyasa,True,...,2003.0,gravity,vwc,pay annually,good,enough,spring,groundwater,3,False
74234,74234,P,0,250.0,4,other,1166.0,dwe,Internal,True,...,2000.0,gravity,vwc,pay monthly,good,insufficient,spring,groundwater,3,True
74235,74235,P,0,250.0,3,rwssp,1166.0,dwe,Lake Tanganyika,True,...,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74236,74236,P,0,250.0,4,other,-7.0,other,Rufiji,True,...,2009.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,3,False
74237,74237,P,0,500.0,3,tasaf,1241.0,other,Lake Tanganyika,True,...,2010.0,handpump,vwc,pay annually,good,enough,machine dbh,groundwater,3,False
74238,74238,P,0,3000.0,4,kkkt,2046.0,commu,Lake Nyasa,True,...,1986.0,gravity,vwc,pay annually,good,enough,spring,groundwater,3,False
74239,74239,P,0,250.0,4,other,347.0,other,Pangani,True,...,2005.0,gravity,other,never pay,good,insufficient,spring,groundwater,3,False
74240,74240,P,0,250.0,3,other,1291.0,other,Lake Nyasa,True,...,2009.0,gravity,vwc,never pay,good,enough,river,surface,3,False
74241,74241,P,0,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,...,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74242,74242,P,0,600.0,3,other,808.0,dwe,Lake Tanganyika,True,...,2009.0,gravity,vwc,pay monthly,good,enough,river,surface,3,False
74243,74243,P,0,250.0,3,other,1641.0,other,Lake Tanganyika,True,...,1995.0,other,vwc,never pay,good,enough,spring,groundwater,3,False
74244,74244,P,0,250.0,3,other,1166.0,dwe,Lake Victoria,True,...,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74245,74245,P,0,250.0,4,danida,34.0,other,Wami / Ruvu,True,...,1988.0,motorpump,vwc,never pay,good,enough,river,surface,3,False
74246,74246,P,0,1000.0,4,other,1166.0,other,Pangani,True,...,1994.0,handpump,vwc,pay annually,salty,insufficient,shallow well,groundwater,3,False
74247,74247,P,0,250.0,3,other,1476.0,other,Internal,True,...,2010.0,gravity,vwc,never pay,good,insufficient,dam,surface,3,False
74248,74248,P,0,250.0,3,other,998.0,dwe,Lake Nyasa,True,...,2009.0,gravity,vwc,never pay,good,insufficient,river,surface,3,False
74249,74249,P,0,250.0,3,gov,481.0,gov,Lake Nyasa,True,...,2008.0,gravity,vwc,never pay,good,dry,spring,groundwater,3,False

In [18]:
df_clean_data.drop(df_clean_data.columns[0], axis = 1, inplace = True)

In [19]:
df_clean_data

,type_data,status_group,amount_tsh,count_month,funder,gps_height,installer,basin,public_meeting,permit,construction_year,extraction_type_class,management,payment,quality_group,quantity,source,source_class,status_group_02,missing_construction_year
0,T,0,6000.0,4,other,1390.0,other,Lake Nyasa,True,False,1999.0,gravity,vwc,pay annually,good,enough,spring,groundwater,2,False
1,T,0,250.0,3,other,1399.0,other,Lake Victoria,Unknown,True,2010.0,gravity,wug,never pay,good,insufficient,rainwater harvesting,surface,2,False
2,T,0,25.0,3,other,686.0,other,Pangani,True,True,2009.0,gravity,vwc,pay per bucket,good,enough,dam,surface,2,False
3,T,0,250.0,3,unicef,263.0,other,Ruvuma / Southern Coast,True,True,1986.0,submersible,vwc,never pay,good,dry,machine dbh,groundwater,0,False
4,T,0,250.0,4,other,1166.0,other,Lake Victoria,True,True,2000.0,gravity,other,never pay,good,seasonal,rainwater harvesting,surface,2,True
5,T,0,20.0,4,other,1166.0,dwe,Pangani,True,True,2009.0,submersible,vwc,pay per bucket,salty,enough,other,unknown,2,False
6,T,0,250.0,4,other,1166.0,other,Internal,True,True,2000.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,0,True
7,T,0,250.0,4,rwssp,1166.0,dwe,Lake Tanganyika,True,True,2000.0,handpump,wug,other,milky,enough,shallow well,groundwater,0,True
8,T,0,250.0,3,other,1166.0,other,Lake Tanganyika,True,True,2000.0,handpump,vwc,never pay,salty,seasonal,machine dbh,groundwater,0,True
9,T,0,250.0,4,other,1166.0,other,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,2,True
10,T,0,250.0,4,other,62.0,other,Wami / Ruvu,True,False,2011.0,submersible,private operator,never pay,salty,enough,machine dbh,groundwater,2,False
11,T,0,200.0,3,danida,1062.0,danida,Lake Nyasa,True,False,1987.0,handpump,wug,pay when scheme fails,good,insufficient,shallow well,groundwater,2,False
12,T,0,250.0,4,world vision,1166.0,other,Internal,True,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,2,True
13,T,0,250.0,3,other,1368.0,other,Pangani,True,True,2009.0,gravity,water board,pay monthly,good,enough,spring,groundwater,2,False
14,T,0,250.0,3,other,1166.0,other,Internal,True,True,2000.0,handpump,wug,never pay,good,enough,shallow well,groundwater,2,True
15,T,0,250.0,4,other,1645.0,dwe,Lake Tanganyika,True,False,1991.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,2,False
16,T,0,500.0,4,unicef,1703.0,dwe,Rufiji,True,True,1978.0,gravity,wua,pay monthly,good,dry,river,surface,0,False
17,T,0,250.0,4,unicef,1656.0,dwe,Rufiji,True,True,1978.0,gravity,wua,pay when scheme fails,good,dry,river,surface,0,False
18,T,0,250.0,4,hesawa,1162.0,dwe,Lake Victoria,Unknown,True,1999.0,other,vwc,never pay,milky,insufficient,spring,groundwater,1,False
19,T,0,500.0,4,danida,1763.0,other,Lake Nyasa,True,True,1992.0,gravity,vwc,pay annually,good,enough,spring,groundwater,2,False
20,T,0,200.0,4,other,2216.0,other,Lake Nyasa,True,False,2008.0,gravity,vwc,pay monthly,good,enough,spring,groundwater,2,False
21,T,0,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,False,2000.0,handpump,wug,other,unknown,unknown,shallow well,groundwater,2,True
22,T,0,250.0,4,unicef,1510.0,dwe,Rufiji,True,True,1978.0,gravity,wua,never pay,good,enough,river,surface,1,False
23,T,0,500.0,3,other,672.0,other,Pangani,True,True,2011.0,gravity,vwc,pay monthly,good,enough,river,surface,2,False
24,T,0,250.0,3,other,1645.0,dwe,Lake Tanganyika,False,True,2009.0,gravity,vwc,other,good,enough,spring,groundwater,2,False
25,T,0,250.0,3,gov,1273.0,dwe,Pangani,True,True,1974.0,gravity,vwc,other,good,enough,spring,groundwater,1,False
26,T,0,500.0,3,other,200.0,other,Ruvuma / Southern Coast,False,False,2011.0,handpump,vwc,pay monthly,good,enough,machine dbh,groundwater,2,False
27,T,0,250.0,4,hesawa,1166.0,dwe,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,2,True
28,T,0,250.0,3,gov,1443.0,other,Pangani,True,True,2000.0,gravity,company,pay monthly,good,insufficient,spring,groundwater,0,False
29,T,0,250.0,3,other,1256.0,other,Pangani,True,True,2002.0,gravity,water board,pay monthly,good,enough,spring,groundwater,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,P,0,250.0,3,other,265.0,other,Ruvuma / Southern Coast,True,False,2001.0,gravity,vwc,never pay,good,seasonal,rainwater harvesting,surface,3,False
74221,P,0,5.0,3,other,1322.0,dwe,Pangani,True,True,2007.0,gravity,water board,pay per bucket,good,enough,river,surface,3,False
74222,P,0,50.0,3,other,640.0,other,Ruvuma / Southern Coast,True,False,1997.0,gravity,other,pay per bucket,good,insufficient,spring,groundwater,3,False
74223,P,0,250.0,4,other,1166.0,other,Lake Nyasa,True,Unknown,2000.0,gravity,parastatal,other,good,enough,spring,groundwater,3,True
74224,P,0,250.0,4,other,574.0,other,Wami / Ruvu,True,True,2008.0,handpump,vwc,never pay,good,insufficient,shallow well,groundwater,3,False
74225,P,0,250.0,3,other,331.0,other,Ruvuma / Southern Coast,True,True,1978.0,handpump,vwc,never pay,good,insufficient,machine dbh,groundwater,3,False
74226,P,0,250.0,3,world vision,1166.0,other,Lake Tanganyika,Unknown,True,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74227,P,0,250.0,4,hesawa,1166.0,other,Lake Victoria,True,True,2000.0,handpump,vwc,pay annually,good,enough,shallow well,groundwater,3,True
74228,P,0,50.0,4,other,78.0,other,Wami / Ruvu,False,False,2000.0,other,private operator,pay per bucket,salty,enough,machine dbh,groundwater,3,True
74229,P,0,250.0,3,gov,836.0,gov,Ruvuma / Southern Coast,Unknown,True,2005.0,gravity,vwc,other,good,enough,spring,groundwater,3,False
74230,P,0,250.0,3,other,1651.0,tcrs,Pangani,True,True,1996.0,gravity,vwc,never pay,good,insufficient,spring,groundwater,3,False
74231,P,0,250.0,3,hesawa,1166.0,dwe,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,salty,enough,shallow well,groundwater,3,True
74232,P,0,250.0,3,kkkt,1393.0,kkkt,Pangani,True,False,2001.0,submersible,vwc,other,fluoride,enough,machine dbh,groundwater,3,False
74233,P,0,1000.0,4,kkkt,1729.0,commu,Lake Nyasa,True,False,2003.0,gravity,vwc,pay annually,good,enough,spring,groundwater,3,False
74234,P,0,250.0,4,other,1166.0,dwe,Internal,True,False,2000.0,gravity,vwc,pay monthly,good,insufficient,spring,groundwater,3,True
74235,P,0,250.0,3,rwssp,1166.0,dwe,Lake Tanganyika,True,True,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74236,P,0,250.0,4,other,-7.0,other,Rufiji,True,False,2009.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,3,False
74237,P,0,500.0,3,tasaf,1241.0,other,Lake Tanganyika,True,False,2010.0,handpump,vwc,pay annually,good,enough,machine dbh,groundwater,3,False
74238,P,0,3000.0,4,kkkt,2046.0,commu,Lake Nyasa,True,False,1986.0,gravity,vwc,pay annually,good,enough,spring,groundwater,3,False
74239,P,0,250.0,4,other,347.0,other,Pangani,True,False,2005.0,gravity,other,never pay,good,insufficient,spring,groundwater,3,False
74240,P,0,250.0,3,other,1291.0,other,Lake Nyasa,True,True,2009.0,gravity,vwc,never pay,good,enough,river,surface,3,False
74241,P,0,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74242,P,0,600.0,3,other,808.0,dwe,Lake Tanganyika,True,True,2009.0,gravity,vwc,pay monthly,good,enough,river,surface,3,False
74243,P,0,250.0,3,other,1641.0,other,Lake Tanganyika,True,False,1995.0,other,vwc,never pay,good,enough,spring,groundwater,3,False
74244,P,0,250.0,3,other,1166.0,dwe,Lake Victoria,True,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,3,True
74245,P,0,250.0,4,danida,34.0,other,Wami / Ruvu,True,True,1988.0,motorpump,vwc,never pay,good,enough,river,surface,3,False
74246,P,0,1000.0,4,other,1166.0,other,Pangani,True,False,1994.0,handpump,vwc,pay annually,salty,insufficient,shallow well,groundwater,3,False
74247,P,0,250.0,3,other,1476.0,other,Internal,True,Unknown,2010.0,gravity,vwc,never pay,good,insufficient,dam,surface,3,False
74248,P,0,250.0,3,other,998.0,dwe,Lake Nyasa,True,True,2009.0,gravity,vwc,never pay,good,insufficient,river,surface,3,False
74249,P,0,250.0,3,gov,481.0,gov,Lake Nyasa,True,True,2008.0,gravity,vwc,never pay,good,dry,spring,groundwater,3,False

In [20]:
def feature2number(df, column_name):
    unique_values = set(df[column_name].tolist())
    transformer_dict = {}
    for index, value in enumerate(unique_values):
        transformer_dict[value] = index
    df[column_name] = df[column_name].apply(lambda y: transformer_dict[y])
    return df

In [23]:
df_clean_data.dtypes

type_data                     object
status_group                   int64
amount_tsh                   float64
count_month                    int64
funder                        object
gps_height                   float64
installer                     object
basin                         object
public_meeting                object
permit                        object
construction_year            float64
extraction_type_class         object
management                    object
payment                       object
quality_group                 object
quantity                      object
source                        object
source_class                  object
status_group_02                int64
missing_construction_year       bool
dtype: object

In [26]:
df_clean_data.status_group = df_clean_data.status_group_02

In [27]:
df_clean_data.status_group

0        2
1        2
2        2
3        0
4        2
5        2
6        0
7        0
8        0
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       0
17       0
18       1
19       2
20       2
21       2
22       1
23       2
24       2
25       1
26       2
27       2
28       0
29       2
        ..
74220    3
74221    3
74222    3
74223    3
74224    3
74225    3
74226    3
74227    3
74228    3
74229    3
74230    3
74231    3
74232    3
74233    3
74234    3
74235    3
74236    3
74237    3
74238    3
74239    3
74240    3
74241    3
74242    3
74243    3
74244    3
74245    3
74246    3
74247    3
74248    3
74249    3
Name: status_group, Length: 74250, dtype: int64

In [29]:
df_clean_data.drop(columns=['status_group_02'], inplace = True)

In [30]:
df_clean_data.dtypes

type_data                     object
status_group                   int64
amount_tsh                   float64
count_month                    int64
funder                        object
gps_height                   float64
installer                     object
basin                         object
public_meeting                object
permit                        object
construction_year            float64
extraction_type_class         object
management                    object
payment                       object
quality_group                 object
quantity                      object
source                        object
source_class                  object
missing_construction_year       bool
dtype: object

In [34]:
numeric_columns = ['status_group', 'amount_tsh','count_month', 'gps_height', 'construction_year', 'missing_construction_year'] 
columns_to_transform = [col for col in df_clean_data.columns if col not in numeric_columns]
for column in columns_to_transform: 
    feature2number(df_clean_data, column)

In [35]:
df_clean_data

,type_data,status_group,amount_tsh,count_month,funder,gps_height,installer,basin,public_meeting,permit,construction_year,extraction_type_class,management,payment,quality_group,quantity,source,source_class,missing_construction_year
0,1,2,6000.0,4,0,1390.0,0,7,2,1,1999.0,2,3,0,4,3,3,1,False
1,1,2,250.0,3,0,1399.0,0,6,1,2,2010.0,2,10,2,4,1,1,0,False
2,1,2,25.0,3,0,686.0,0,5,2,2,2009.0,2,3,3,4,3,4,0,False
3,1,0,250.0,3,2,263.0,0,4,2,2,1986.0,1,3,2,4,2,2,1,False
4,1,2,250.0,4,0,1166.0,0,6,2,2,2000.0,2,0,2,4,4,1,0,True
5,1,2,20.0,4,0,1166.0,3,5,2,2,2009.0,1,3,3,5,3,0,2,False
6,1,0,250.0,4,0,1166.0,0,0,2,2,2000.0,6,3,2,4,3,2,1,True
7,1,0,250.0,4,1,1166.0,3,3,2,2,2000.0,6,10,1,2,3,8,1,True
8,1,0,250.0,3,0,1166.0,0,3,2,2,2000.0,6,3,2,5,4,2,1,True
9,1,2,250.0,4,0,1166.0,0,6,2,2,2000.0,6,3,2,4,3,8,1,True
10,1,2,250.0,4,0,62.0,0,1,2,1,2011.0,1,9,2,5,3,2,1,False
11,1,2,200.0,3,6,1062.0,5,7,2,1,1987.0,6,10,4,4,1,8,1,False
12,1,2,250.0,4,7,1166.0,0,0,2,1,2000.0,6,10,1,4,3,8,1,True
13,1,2,250.0,3,0,1368.0,0,5,2,2,2009.0,2,4,5,4,3,3,1,False
14,1,2,250.0,3,0,1166.0,0,0,2,2,2000.0,6,10,2,4,3,8,1,True
15,1,2,250.0,4,0,1645.0,3,3,2,1,1991.0,6,3,2,4,3,2,1,False
16,1,0,500.0,4,2,1703.0,3,2,2,2,1978.0,2,5,5,4,2,6,0,False
17,1,0,250.0,4,2,1656.0,3,2,2,2,1978.0,2,5,4,4,2,6,0,False
18,1,1,250.0,4,9,1162.0,3,6,1,2,1999.0,0,3,2,2,1,3,1,False
19,1,2,500.0,4,6,1763.0,0,7,2,2,1992.0,2,3,0,4,3,3,1,False
20,1,2,200.0,4,0,2216.0,0,7,2,1,2008.0,2,3,5,4,3,3,1,False
21,1,2,250.0,3,0,1166.0,3,6,1,1,2000.0,6,10,1,0,0,8,1,True
22,1,1,250.0,4,2,1510.0,3,2,2,2,1978.0,2,5,2,4,3,6,0,False
23,1,2,500.0,3,0,672.0,0,5,2,2,2011.0,2,3,5,4,3,6,0,False
24,1,2,250.0,3,0,1645.0,3,3,0,2,2009.0,2,3,1,4,3,3,1,False
25,1,1,250.0,3,4,1273.0,3,5,2,2,1974.0,2,3,1,4,3,3,1,False
26,1,2,500.0,3,0,200.0,0,4,0,1,2011.0,6,3,5,4,3,2,1,False
27,1,2,250.0,4,9,1166.0,3,6,2,2,2000.0,6,3,2,4,3,8,1,True
28,1,0,250.0,3,4,1443.0,0,5,2,2,2000.0,2,8,5,4,1,3,1,False
29,1,2,250.0,3,0,1256.0,0,5,2,2,2002.0,2,4,5,4,3,3,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,0,3,250.0,3,0,265.0,0,4,2,1,2001.0,2,3,2,4,4,1,0,False
74221,0,3,5.0,3,0,1322.0,3,5,2,2,2007.0,2,4,3,4,3,6,0,False
74222,0,3,50.0,3,0,640.0,0,4,2,1,1997.0,2,0,3,4,1,3,1,False
74223,0,3,250.0,4,0,1166.0,0,7,2,0,2000.0,2,7,1,4,3,3,1,True
74224,0,3,250.0,4,0,574.0,0,1,2,2,2008.0,6,3,2,4,1,8,1,False
74225,0,3,250.0,3,0,331.0,0,4,2,2,1978.0,6,3,2,4,1,2,1,False
74226,0,3,250.0,3,7,1166.0,0,3,1,2,2000.0,6,10,1,4,3,8,1,True
74227,0,3,250.0,4,9,1166.0,0,6,2,2,2000.0,6,3,0,4,3,8,1,True
74228,0,3,50.0,4,0,78.0,0,1,0,1,2000.0,0,9,3,5,3,2,1,True
74229,0,3,250.0,3,4,836.0,4,4,1,2,2005.0,2,3,1,4,3,3,1,False
74230,0,3,250.0,3,0,1651.0,2,5,2,2,1996.0,2,3,2,4,1,3,1,False
74231,0,3,250.0,3,9,1166.0,3,6,2,2,2000.0,6,3,2,5,3,8,1,True
74232,0,3,250.0,3,10,1393.0,9,5,2,1,2001.0,1,3,1,1,3,2,1,False
74233,0,3,1000.0,4,10,1729.0,1,7,2,1,2003.0,2,3,0,4,3,3,1,False
74234,0,3,250.0,4,0,1166.0,3,0,2,1,2000.0,2,3,5,4,1,3,1,True
74235,0,3,250.0,3,1,1166.0,3,3,2,2,2000.0,6,10,1,4,3,8,1,True
74236,0,3,250.0,4,0,-7.0,0,2,2,1,2009.0,6,3,2,4,3,8,1,False
74237,0,3,500.0,3,3,1241.0,0,3,2,1,2010.0,6,3,0,4,3,2,1,False
74238,0,3,3000.0,4,10,2046.0,1,7,2,1,1986.0,2,3,0,4,3,3,1,False
74239,0,3,250.0,4,0,347.0,0,5,2,1,2005.0,2,0,2,4,1,3,1,False
74240,0,3,250.0,3,0,1291.0,0,7,2,2,2009.0,2,3,2,4,3,6,0,False
74241,0,3,250.0,3,0,1166.0,3,6,1,1,2000.0,6,10,1,4,3,8,1,True
74242,0,3,600.0,3,0,808.0,3,3,2,2,2009.0,2,3,5,4,3,6,0,False
74243,0,3,250.0,3,0,1641.0,0,3,2,1,1995.0,0,3,2,4,3,3,1,False
74244,0,3,250.0,3,0,1166.0,3,6,2,1,2000.0,6,10,1,4,3,8,1,True
74245,0,3,250.0,4,6,34.0,0,1,2,2,1988.0,4,3,2,4,3,6,0,False
74246,0,3,1000.0,4,0,1166.0,0,5,2,1,1994.0,6,3,0,5,1,8,1,False
74247,0,3,250.0,3,0,1476.0,0,0,2,0,2010.0,2,3,2,4,1,4,0,False
74248,0,3,250.0,3,0,998.0,3,7,2,2,2009.0,2,3,2,4,1,6,0,False
74249,0,3,250.0,3,4,481.0,4,7,2,2,2008.0,2,3,2,4,2,3,1,False

In [36]:
df_clean_data.to_csv('numeric_data.csv')