In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
df_clean_data = pd.read_csv('clean_data.csv')

In [6]:
df_clean_data

,Unnamed: 0,status_group,amount_tsh,count_month,funder,gps_height,installer,basin,public_meeting,permit,construction_year,extraction_type_class,management,payment,quality_group,quantity,source,source_class,missing_construction_year
0,0,2,6000.0,4,other,1390.0,other,Lake Nyasa,True,False,1999.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
1,1,2,250.0,3,other,1399.0,other,Lake Victoria,Unknown,True,2010.0,gravity,wug,never pay,good,insufficient,rainwater harvesting,surface,False
2,2,2,25.0,3,other,686.0,other,Pangani,True,True,2009.0,gravity,vwc,pay per bucket,good,enough,dam,surface,False
3,3,0,250.0,3,unicef,263.0,other,Ruvuma / Southern Coast,True,True,1986.0,submersible,vwc,never pay,good,dry,machine dbh,groundwater,False
4,4,2,250.0,4,other,1166.0,other,Lake Victoria,True,True,2000.0,gravity,other,never pay,good,seasonal,rainwater harvesting,surface,True
5,5,2,20.0,4,other,1166.0,dwe,Pangani,True,True,2009.0,submersible,vwc,pay per bucket,salty,enough,other,unknown,False
6,6,0,250.0,4,other,1166.0,other,Internal,True,True,2000.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,True
7,7,0,250.0,4,rwssp,1166.0,dwe,Lake Tanganyika,True,True,2000.0,handpump,wug,other,milky,enough,shallow well,groundwater,True
8,8,0,250.0,3,other,1166.0,other,Lake Tanganyika,True,True,2000.0,handpump,vwc,never pay,salty,seasonal,machine dbh,groundwater,True
9,9,2,250.0,4,other,1166.0,other,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,True
10,10,2,250.0,4,other,62.0,other,Wami / Ruvu,True,False,2011.0,submersible,private operator,never pay,salty,enough,machine dbh,groundwater,False
11,11,2,200.0,3,danida,1062.0,danida,Lake Nyasa,True,False,1987.0,handpump,wug,pay when scheme fails,good,insufficient,shallow well,groundwater,False
12,12,2,250.0,4,world vision,1166.0,other,Internal,True,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
13,13,2,250.0,3,other,1368.0,other,Pangani,True,True,2009.0,gravity,water board,pay monthly,good,enough,spring,groundwater,False
14,14,2,250.0,3,other,1166.0,other,Internal,True,True,2000.0,handpump,wug,never pay,good,enough,shallow well,groundwater,True
15,15,2,250.0,4,other,1645.0,dwe,Lake Tanganyika,True,False,1991.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,False
16,16,0,500.0,4,unicef,1703.0,dwe,Rufiji,True,True,1978.0,gravity,wua,pay monthly,good,dry,river,surface,False
17,17,0,250.0,4,unicef,1656.0,dwe,Rufiji,True,True,1978.0,gravity,wua,pay when scheme fails,good,dry,river,surface,False
18,18,1,250.0,4,hesawa,1162.0,dwe,Lake Victoria,Unknown,True,1999.0,other,vwc,never pay,milky,insufficient,spring,groundwater,False
19,19,2,500.0,4,danida,1763.0,other,Lake Nyasa,True,True,1992.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
20,20,2,200.0,4,other,2216.0,other,Lake Nyasa,True,False,2008.0,gravity,vwc,pay monthly,good,enough,spring,groundwater,False
21,21,2,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,False,2000.0,handpump,wug,other,unknown,unknown,shallow well,groundwater,True
22,22,1,250.0,4,unicef,1510.0,dwe,Rufiji,True,True,1978.0,gravity,wua,never pay,good,enough,river,surface,False
23,23,2,500.0,3,other,672.0,other,Pangani,True,True,2011.0,gravity,vwc,pay monthly,good,enough,river,surface,False
24,24,2,250.0,3,other,1645.0,dwe,Lake Tanganyika,False,True,2009.0,gravity,vwc,other,good,enough,spring,groundwater,False
25,25,1,250.0,3,gov,1273.0,dwe,Pangani,True,True,1974.0,gravity,vwc,other,good,enough,spring,groundwater,False
26,26,2,500.0,3,other,200.0,other,Ruvuma / Southern Coast,False,False,2011.0,handpump,vwc,pay monthly,good,enough,machine dbh,groundwater,False
27,27,2,250.0,4,hesawa,1166.0,dwe,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,True
28,28,0,250.0,3,gov,1443.0,other,Pangani,True,True,2000.0,gravity,company,pay monthly,good,insufficient,spring,groundwater,False
29,29,2,250.0,3,other,1256.0,other,Pangani,True,True,2002.0,gravity,water board,pay monthly,good,enough,spring,groundwater,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,74220,3,250.0,3,other,265.0,other,Ruvuma / Southern Coast,True,False,2001.0,gravity,vwc,never pay,good,seasonal,rainwater harvesting,surface,False
74221,74221,3,5.0,3,other,1322.0,dwe,Pangani,True,True,2007.0,gravity,water board,pay per bucket,good,enough,river,surface,False
74222,74222,3,50.0,3,other,640.0,other,Ruvuma / Southern Coast,True,False,1997.0,gravity,other,pay per bucket,good,insufficient,spring,groundwater,False
74223,74223,3,250.0,4,other,1166.0,other,Lake Nyasa,True,Unknown,2000.0,gravity,parastatal,other,good,enough,spring,groundwater,True
74224,74224,3,250.0,4,other,574.0,other,Wami / Ruvu,True,True,2008.0,handpump,vwc,never pay,good,insufficient,shallow well,groundwater,False
74225,74225,3,250.0,3,other,331.0,other,Ruvuma / Southern Coast,True,True,1978.0,handpump,vwc,never pay,good,insufficient,machine dbh,groundwater,False
74226,74226,3,250.0,3,world vision,1166.0,other,Lake Tanganyika,Unknown,True,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74227,74227,3,250.0,4,hesawa,1166.0,other,Lake Victoria,True,True,2000.0,handpump,vwc,pay annually,good,enough,shallow well,groundwater,True
74228,74228,3,50.0,4,other,78.0,other,Wami / Ruvu,False,False,2000.0,other,private operator,pay per bucket,salty,enough,machine dbh,groundwater,True
74229,74229,3,250.0,3,gov,836.0,gov,Ruvuma / Southern Coast,Unknown,True,2005.0,gravity,vwc,other,good,enough,spring,groundwater,False
74230,74230,3,250.0,3,other,1651.0,tcrs,Pangani,True,True,1996.0,gravity,vwc,never pay,good,insufficient,spring,groundwater,False
74231,74231,3,250.0,3,hesawa,1166.0,dwe,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,salty,enough,shallow well,groundwater,True
74232,74232,3,250.0,3,kkkt,1393.0,kkkt,Pangani,True,False,2001.0,submersible,vwc,other,fluoride,enough,machine dbh,groundwater,False
74233,74233,3,1000.0,4,kkkt,1729.0,commu,Lake Nyasa,True,False,2003.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
74234,74234,3,250.0,4,other,1166.0,dwe,Internal,True,False,2000.0,gravity,vwc,pay monthly,good,insufficient,spring,groundwater,True
74235,74235,3,250.0,3,rwssp,1166.0,dwe,Lake Tanganyika,True,True,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74236,74236,3,250.0,4,other,-7.0,other,Rufiji,True,False,2009.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,False
74237,74237,3,500.0,3,tasaf,1241.0,other,Lake Tanganyika,True,False,2010.0,handpump,vwc,pay annually,good,enough,machine dbh,groundwater,False
74238,74238,3,3000.0,4,kkkt,2046.0,commu,Lake Nyasa,True,False,1986.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
74239,74239,3,250.0,4,other,347.0,other,Pangani,True,False,2005.0,gravity,other,never pay,good,insufficient,spring,groundwater,False
74240,74240,3,250.0,3,other,1291.0,other,Lake Nyasa,True,True,2009.0,gravity,vwc,never pay,good,enough,river,surface,False
74241,74241,3,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74242,74242,3,600.0,3,other,808.0,dwe,Lake Tanganyika,True,True,2009.0,gravity,vwc,pay monthly,good,enough,river,surface,False
74243,74243,3,250.0,3,other,1641.0,other,Lake Tanganyika,True,False,1995.0,other,vwc,never pay,good,enough,spring,groundwater,False
74244,74244,3,250.0,3,other,1166.0,dwe,Lake Victoria,True,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74245,74245,3,250.0,4,danida,34.0,other,Wami / Ruvu,True,True,1988.0,motorpump,vwc,never pay,good,enough,river,surface,False
74246,74246,3,1000.0,4,other,1166.0,other,Pangani,True,False,1994.0,handpump,vwc,pay annually,salty,insufficient,shallow well,groundwater,False
74247,74247,3,250.0,3,other,1476.0,other,Internal,True,Unknown,2010.0,gravity,vwc,never pay,good,insufficient,dam,surface,False
74248,74248,3,250.0,3,other,998.0,dwe,Lake Nyasa,True,True,2009.0,gravity,vwc,never pay,good,insufficient,river,surface,False
74249,74249,3,250.0,3,gov,481.0,gov,Lake Nyasa,True,True,2008.0,gravity,vwc,never pay,good,dry,spring,groundwater,False

In [7]:
df_clean_data.drop(df_clean_data.columns[0], axis = 1, inplace = True)

In [8]:
df_clean_data

,status_group,amount_tsh,count_month,funder,gps_height,installer,basin,public_meeting,permit,construction_year,extraction_type_class,management,payment,quality_group,quantity,source,source_class,missing_construction_year
0,2,6000.0,4,other,1390.0,other,Lake Nyasa,True,False,1999.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
1,2,250.0,3,other,1399.0,other,Lake Victoria,Unknown,True,2010.0,gravity,wug,never pay,good,insufficient,rainwater harvesting,surface,False
2,2,25.0,3,other,686.0,other,Pangani,True,True,2009.0,gravity,vwc,pay per bucket,good,enough,dam,surface,False
3,0,250.0,3,unicef,263.0,other,Ruvuma / Southern Coast,True,True,1986.0,submersible,vwc,never pay,good,dry,machine dbh,groundwater,False
4,2,250.0,4,other,1166.0,other,Lake Victoria,True,True,2000.0,gravity,other,never pay,good,seasonal,rainwater harvesting,surface,True
5,2,20.0,4,other,1166.0,dwe,Pangani,True,True,2009.0,submersible,vwc,pay per bucket,salty,enough,other,unknown,False
6,0,250.0,4,other,1166.0,other,Internal,True,True,2000.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,True
7,0,250.0,4,rwssp,1166.0,dwe,Lake Tanganyika,True,True,2000.0,handpump,wug,other,milky,enough,shallow well,groundwater,True
8,0,250.0,3,other,1166.0,other,Lake Tanganyika,True,True,2000.0,handpump,vwc,never pay,salty,seasonal,machine dbh,groundwater,True
9,2,250.0,4,other,1166.0,other,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,True
10,2,250.0,4,other,62.0,other,Wami / Ruvu,True,False,2011.0,submersible,private operator,never pay,salty,enough,machine dbh,groundwater,False
11,2,200.0,3,danida,1062.0,danida,Lake Nyasa,True,False,1987.0,handpump,wug,pay when scheme fails,good,insufficient,shallow well,groundwater,False
12,2,250.0,4,world vision,1166.0,other,Internal,True,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
13,2,250.0,3,other,1368.0,other,Pangani,True,True,2009.0,gravity,water board,pay monthly,good,enough,spring,groundwater,False
14,2,250.0,3,other,1166.0,other,Internal,True,True,2000.0,handpump,wug,never pay,good,enough,shallow well,groundwater,True
15,2,250.0,4,other,1645.0,dwe,Lake Tanganyika,True,False,1991.0,handpump,vwc,never pay,good,enough,machine dbh,groundwater,False
16,0,500.0,4,unicef,1703.0,dwe,Rufiji,True,True,1978.0,gravity,wua,pay monthly,good,dry,river,surface,False
17,0,250.0,4,unicef,1656.0,dwe,Rufiji,True,True,1978.0,gravity,wua,pay when scheme fails,good,dry,river,surface,False
18,1,250.0,4,hesawa,1162.0,dwe,Lake Victoria,Unknown,True,1999.0,other,vwc,never pay,milky,insufficient,spring,groundwater,False
19,2,500.0,4,danida,1763.0,other,Lake Nyasa,True,True,1992.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
20,2,200.0,4,other,2216.0,other,Lake Nyasa,True,False,2008.0,gravity,vwc,pay monthly,good,enough,spring,groundwater,False
21,2,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,False,2000.0,handpump,wug,other,unknown,unknown,shallow well,groundwater,True
22,1,250.0,4,unicef,1510.0,dwe,Rufiji,True,True,1978.0,gravity,wua,never pay,good,enough,river,surface,False
23,2,500.0,3,other,672.0,other,Pangani,True,True,2011.0,gravity,vwc,pay monthly,good,enough,river,surface,False
24,2,250.0,3,other,1645.0,dwe,Lake Tanganyika,False,True,2009.0,gravity,vwc,other,good,enough,spring,groundwater,False
25,1,250.0,3,gov,1273.0,dwe,Pangani,True,True,1974.0,gravity,vwc,other,good,enough,spring,groundwater,False
26,2,500.0,3,other,200.0,other,Ruvuma / Southern Coast,False,False,2011.0,handpump,vwc,pay monthly,good,enough,machine dbh,groundwater,False
27,2,250.0,4,hesawa,1166.0,dwe,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,True
28,0,250.0,3,gov,1443.0,other,Pangani,True,True,2000.0,gravity,company,pay monthly,good,insufficient,spring,groundwater,False
29,2,250.0,3,other,1256.0,other,Pangani,True,True,2002.0,gravity,water board,pay monthly,good,enough,spring,groundwater,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,3,250.0,3,other,265.0,other,Ruvuma / Southern Coast,True,False,2001.0,gravity,vwc,never pay,good,seasonal,rainwater harvesting,surface,False
74221,3,5.0,3,other,1322.0,dwe,Pangani,True,True,2007.0,gravity,water board,pay per bucket,good,enough,river,surface,False
74222,3,50.0,3,other,640.0,other,Ruvuma / Southern Coast,True,False,1997.0,gravity,other,pay per bucket,good,insufficient,spring,groundwater,False
74223,3,250.0,4,other,1166.0,other,Lake Nyasa,True,Unknown,2000.0,gravity,parastatal,other,good,enough,spring,groundwater,True
74224,3,250.0,4,other,574.0,other,Wami / Ruvu,True,True,2008.0,handpump,vwc,never pay,good,insufficient,shallow well,groundwater,False
74225,3,250.0,3,other,331.0,other,Ruvuma / Southern Coast,True,True,1978.0,handpump,vwc,never pay,good,insufficient,machine dbh,groundwater,False
74226,3,250.0,3,world vision,1166.0,other,Lake Tanganyika,Unknown,True,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74227,3,250.0,4,hesawa,1166.0,other,Lake Victoria,True,True,2000.0,handpump,vwc,pay annually,good,enough,shallow well,groundwater,True
74228,3,50.0,4,other,78.0,other,Wami / Ruvu,False,False,2000.0,other,private operator,pay per bucket,salty,enough,machine dbh,groundwater,True
74229,3,250.0,3,gov,836.0,gov,Ruvuma / Southern Coast,Unknown,True,2005.0,gravity,vwc,other,good,enough,spring,groundwater,False
74230,3,250.0,3,other,1651.0,tcrs,Pangani,True,True,1996.0,gravity,vwc,never pay,good,insufficient,spring,groundwater,False
74231,3,250.0,3,hesawa,1166.0,dwe,Lake Victoria,True,True,2000.0,handpump,vwc,never pay,salty,enough,shallow well,groundwater,True
74232,3,250.0,3,kkkt,1393.0,kkkt,Pangani,True,False,2001.0,submersible,vwc,other,fluoride,enough,machine dbh,groundwater,False
74233,3,1000.0,4,kkkt,1729.0,commu,Lake Nyasa,True,False,2003.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
74234,3,250.0,4,other,1166.0,dwe,Internal,True,False,2000.0,gravity,vwc,pay monthly,good,insufficient,spring,groundwater,True
74235,3,250.0,3,rwssp,1166.0,dwe,Lake Tanganyika,True,True,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74236,3,250.0,4,other,-7.0,other,Rufiji,True,False,2009.0,handpump,vwc,never pay,good,enough,shallow well,groundwater,False
74237,3,500.0,3,tasaf,1241.0,other,Lake Tanganyika,True,False,2010.0,handpump,vwc,pay annually,good,enough,machine dbh,groundwater,False
74238,3,3000.0,4,kkkt,2046.0,commu,Lake Nyasa,True,False,1986.0,gravity,vwc,pay annually,good,enough,spring,groundwater,False
74239,3,250.0,4,other,347.0,other,Pangani,True,False,2005.0,gravity,other,never pay,good,insufficient,spring,groundwater,False
74240,3,250.0,3,other,1291.0,other,Lake Nyasa,True,True,2009.0,gravity,vwc,never pay,good,enough,river,surface,False
74241,3,250.0,3,other,1166.0,dwe,Lake Victoria,Unknown,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74242,3,600.0,3,other,808.0,dwe,Lake Tanganyika,True,True,2009.0,gravity,vwc,pay monthly,good,enough,river,surface,False
74243,3,250.0,3,other,1641.0,other,Lake Tanganyika,True,False,1995.0,other,vwc,never pay,good,enough,spring,groundwater,False
74244,3,250.0,3,other,1166.0,dwe,Lake Victoria,True,False,2000.0,handpump,wug,other,good,enough,shallow well,groundwater,True
74245,3,250.0,4,danida,34.0,other,Wami / Ruvu,True,True,1988.0,motorpump,vwc,never pay,good,enough,river,surface,False
74246,3,1000.0,4,other,1166.0,other,Pangani,True,False,1994.0,handpump,vwc,pay annually,salty,insufficient,shallow well,groundwater,False
74247,3,250.0,3,other,1476.0,other,Internal,True,Unknown,2010.0,gravity,vwc,never pay,good,insufficient,dam,surface,False
74248,3,250.0,3,other,998.0,dwe,Lake Nyasa,True,True,2009.0,gravity,vwc,never pay,good,insufficient,river,surface,False
74249,3,250.0,3,gov,481.0,gov,Lake Nyasa,True,True,2008.0,gravity,vwc,never pay,good,dry,spring,groundwater,False

In [9]:
def feature2number(df, column_name):
    unique_values = set(df[column_name].tolist())
    transformer_dict = {}
    for index, value in enumerate(unique_values):
        transformer_dict[value] = index
    df[column_name] = df[column_name].apply(lambda y: transformer_dict[y])
    return df

In [10]:
df_clean_data.dtypes

status_group                   int64
amount_tsh                   float64
count_month                    int64
funder                        object
gps_height                   float64
installer                     object
basin                         object
public_meeting                object
permit                        object
construction_year            float64
extraction_type_class         object
management                    object
payment                       object
quality_group                 object
quantity                      object
source                        object
source_class                  object
missing_construction_year       bool
dtype: object

In [12]:
df_clean_data.status_group

0        2
1        2
2        2
3        0
4        2
5        2
6        0
7        0
8        0
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       0
17       0
18       1
19       2
20       2
21       2
22       1
23       2
24       2
25       1
26       2
27       2
28       0
29       2
        ..
74220    3
74221    3
74222    3
74223    3
74224    3
74225    3
74226    3
74227    3
74228    3
74229    3
74230    3
74231    3
74232    3
74233    3
74234    3
74235    3
74236    3
74237    3
74238    3
74239    3
74240    3
74241    3
74242    3
74243    3
74244    3
74245    3
74246    3
74247    3
74248    3
74249    3
Name: status_group, Length: 74250, dtype: int64

In [14]:
df_clean_data.dtypes

status_group                   int64
amount_tsh                   float64
count_month                    int64
funder                        object
gps_height                   float64
installer                     object
basin                         object
public_meeting                object
permit                        object
construction_year            float64
extraction_type_class         object
management                    object
payment                       object
quality_group                 object
quantity                      object
source                        object
source_class                  object
missing_construction_year       bool
dtype: object

In [15]:
numeric_columns = ['status_group', 'amount_tsh','count_month', 
                   'gps_height', 'construction_year', 
                   'missing_construction_year'] 
columns_to_transform = [col for col in df_clean_data.columns if col not in numeric_columns]
for column in columns_to_transform: 
    feature2number(df_clean_data, column)

In [18]:
df_clean_data.head()

,status_group,amount_tsh,count_month,funder,gps_height,installer,basin,public_meeting,permit,construction_year,extraction_type_class,management,payment,quality_group,quantity,source,source_class,missing_construction_year
0,2,6000.0,4,6,1390.0,4,7,2,1,1999.0,5,9,5,5,3,1,0,False
1,2,250.0,3,6,1399.0,4,8,0,2,2010.0,5,2,1,5,0,7,2,False
2,2,25.0,3,6,686.0,4,2,2,2,2009.0,5,9,4,5,3,2,2,False
3,0,250.0,3,1,263.0,4,4,2,2,1986.0,0,9,1,5,4,6,0,False
4,2,250.0,4,6,1166.0,4,8,2,2,2000.0,5,7,1,5,2,7,2,True

In [19]:
df_clean_data.to_csv('numeric_data.csv')

In [20]:
df_train_test = df_clean_data[df_clean_data['status_group'] != 3]

In [21]:
df_train_test.status_group.value_counts()

2    32102
0    23018
1     4280
Name: status_group, dtype: int64

In [23]:
df_to_predict = df_clean_data[df_clean_data['status_group'] == 3]

In [24]:
df_to_predict.status_group.value_counts()

3    14850
Name: status_group, dtype: int64

In [25]:
df_train_test.to_csv('train_test_data.csv')
df_to_predict.to_csv('predict_data.csv')

In [30]:
Xtrain = df_train_test.drop('status_group', axis = 1)

In [31]:
ytrain = df_train_test['status_group']

In [32]:
ytrain.value_counts()

2    32102
0    23018
1     4280
Name: status_group, dtype: int64

In [33]:
X_learn, X_test, y_learn, y_test = train_test_split(Xtrain, ytrain, test_size = 0.3)

In [50]:
rfc = RandomForestClassifier(n_estimators = 100)

In [51]:
rfc.fit(X_learn, y_learn)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [52]:
rfc.score(X_learn, y_learn)

0.93860028860028855

In [53]:
rfc.score(X_test, y_test)

0.77766554433221102

In [55]:
predicted_results = rfc.predict(df_to_predict.drop(['status_group'], axis = 1))

In [56]:
predicted_results.size

14850

In [80]:
from sklearn.metrics import classification_report

In [81]:
predicted = rfc.predict(X_test)

In [82]:
report = classification_report(y_test, predicted)

In [86]:
target_names = ['non functional 0', 'functional needs repair 1', 'functional 2']

In [90]:
report = classification_report(y_test, predicted, target_names = target_names)

In [91]:
print(report)

                           precision    recall  f1-score   support

         non functional 0       0.81      0.75      0.78      6927
functional needs repair 1       0.41      0.29      0.34      1246
             functional 2       0.79      0.86      0.82      9647

              avg / total       0.77      0.78      0.77     17820

In [57]:
pd.Series(data = predicted_results)

0        0
1        0
2        2
3        0
4        2
5        2
6        0
7        0
8        0
9        2
10       2
11       0
12       0
13       2
14       2
15       2
16       0
17       0
18       2
19       0
20       2
21       2
22       0
23       0
24       2
25       2
26       0
27       0
28       1
29       0
        ..
14820    0
14821    2
14822    1
14823    2
14824    0
14825    0
14826    2
14827    2
14828    2
14829    2
14830    0
14831    2
14832    0
14833    2
14834    2
14835    2
14836    2
14837    2
14838    2
14839    2
14840    2
14841    2
14842    1
14843    2
14844    2
14845    0
14846    2
14847    2
14848    2
14849    0
Length: 14850, dtype: int64

In [58]:
df_predicted_results = pd.read_csv('SubmissionFormat.csv')

In [59]:
df_predicted_results.shape

(14850, 2)

In [60]:
df_submit = pd.concat([df_predicted_results, pd.Series(data = predicted_results)], axis=1)

In [61]:
df_submit['status_group'] = df_submit[0]

In [62]:
df_submit.drop(df_submit.columns[2], axis = 1, inplace = True)

In [63]:
df_submit.head(10)

      id  status_group
0  50785             0
1  51630             0
2  17168             2
3  45559             0
4  49871             2
5  52449             2
6  24806             0
7  28965             0
8  36301             0
9  54122             2

In [64]:
df_submit.to_csv('submit_01.csv')

In [94]:
df_submit.status_group.value_counts()

functional                 8694
non functional             5422
functional needs repair     734
Name: status_group, dtype: int64

In [65]:
status_group_replace = {2:'functional', 1: 'functional needs repair', 0:'non functional'}

df_submit['status_group'] = df_submit.status_group.replace(status_group_replace)
df_submit['status_group']

0                 non functional
1                 non functional
2                     functional
3                 non functional
4                     functional
5                     functional
6                 non functional
7                 non functional
8                 non functional
9                     functional
10                    functional
11                non functional
12                non functional
13                    functional
14                    functional
15                    functional
16                non functional
17                non functional
18                    functional
19                non functional
20                    functional
21                    functional
22                non functional
23                non functional
24                    functional
25                    functional
26                non functional
27                non functional
28       functional needs repair
29                non functional
                  ...
14820             non functional
14821                 functional
14822    functional needs repair
14823                 functional
14824             non functional
14825             non functional
14826                 functional
14827                 functional
14828                 functional
14829                 functional
14830             non functional
14831                 functional
14832             non functional
14833                 functional
14834                 functional
14835                 functional
14836                 functional
14837                 functional
14838                 functional
14839                 functional
14840                 functional
14841                 functional
14842    functional needs repair
14843                 functional
14844                 functional
14845             non functional
14846                 functional
14847                 functional
14848                 functional
14849             non functional
Name: status_group, Length: 14850, dtype: object

In [66]:
df_submit.head(10)

      id    status_group
0  50785  non functional
1  51630  non functional
2  17168      functional
3  45559  non functional
4  49871      functional
5  52449      functional
6  24806  non functional
7  28965  non functional
8  36301  non functional
9  54122      functional

In [67]:
df_submit.to_csv('submit_02.csv')

In [68]:
xx01 = df_train_test[df_train_test['status_group'] == 1]

In [69]:
xx01.shape

(4280, 18)

In [70]:
xx02 = df_train_test[df_train_test['status_group'] == 0]

In [71]:
xx02.shape

(23018, 18)

In [72]:
xx03 = df_train_test[df_train_test['status_group'] == 2]

In [73]:
xx03.shape

(32102, 18)

In [74]:
randomxx02 = xx02.sample(n=4280)

In [75]:
randomxx03 = xx03.sample(n=4280)

In [76]:
df_balanced = xx01.append(randomxx02).append(randomxx03)

In [77]:
df_balanced = df_balanced.sample(frac = 1)

In [78]:
df_balanced.to_csv('df_balanced_sample.csv')